export const countryFlagMap: Record<string, string> = {
   "China": "cn.png",
  "India": "in.png",
  "Indonesia": "id.png",
  "Pakistan": "pk.png",
  "Bangladesh": "bd.png",
  "Japan": "jp.png",
  "Philippines": "ph.png",
  "Vietnam": "vn.png",
  "Thailand": "th.png",
  "Myanmar": "mm.png",
  "South Korea": "kr.png",
  "North Korea": "kp.png",
  "Malaysia": "my.png",
  "Nepal": "np.png",
  "Sri Lanka": "lk.png",
  "Cambodia": "kh.png",
  "Laos": "la.png",
  "Mongolia": "mn.png",
  "Taiwan": "tw.png",
  "Afghanistan": "af.png",
  "Saudi Arabia": "sa.png",
  "Iraq": "iq.png",
  "Iran": "ir.png",
  "Israel": "il.png",
  "Jordan": "jo.png",
  "Kuwait": "kw.png",
  "Lebanon": "lb.png",
  "Oman": "om.png",
  "Qatar": "qa.png",
  "Syria": "sy.png",
  "United Arab Emirates": "ae.png",
  "Yemen": "ye.png",
  "Bahrain": "bh.png",
  "Bhutan": "bt.png",
  "Brunei": "bn.png",
  "Timor-Leste": "tl.png",
  "Armenia": "am.png",
  "Azerbaijan": "az.png",
  "Georgia": "ge.png",
  "Kazakhstan": "kz.png",
  "Kyrgyzstan": "kg.png",
  "Turkmenistan": "tm.png",
  "Uzbekistan": "uz.png",
  "Turkey": "tr.png",

  // Europe
  "Germany": "de.png",
  "France": "fr.png",
  "United Kingdom": "gb.png",
  "Italy": "it.png",
  "Spain": "es.png",
  "Ukraine": "ua.png",
  "Poland": "pl.png",
  "Romania": "ro.png",
  "Netherlands": "nl.png",
  "Belgium": "be.png",
  "Greece": "gr.png",
  "Portugal": "pt.png",
  "Sweden": "se.png",
  "Norway": "no.png",
  "Finland": "fi.png",
  "Denmark": "dk.png",
  "Ireland": "ie.png",
  "Austria": "at.png",
  "Switzerland": "ch.png",
  "Hungary": "hu.png",
  "Czech Republic": "cz.png",
  "Slovakia": "sk.png",
  "Bulgaria": "bg.png",
  "Croatia": "hr.png",
  "Serbia": "rs.png",
  "Belarus": "by.png",
  "Lithuania": "lt.png",
  "Latvia": "lv.png",
  "Estonia": "ee.png",
  "Slovenia": "si.png",
  "Luxembourg": "lu.png",
  "Iceland": "is.png",
  "Malta": "mt.png",
  "Cyprus": "cy.png",
  "Monaco": "mc.png",
  "Liechtenstein": "li.png",
  "Andorra": "ad.png",
  "San Marino": "sm.png",
  "Vatican": "va.png",
  "North Macedonia": "mk.png",
  "Montenegro": "me.png",
  "Bosnia and Herzegovina": "ba.png",
  "Albania": "al.png",
  "Moldova": "md.png",
  "Russia": "ru.png",

  // Africa
  "Nigeria": "ng.png",
  "Ethiopia": "et.png",
  "Egypt": "eg.png",
  "DR Congo": "cd.png",
  "South Africa": "za.png",
  "Kenya": "ke.png",
  "Sudan": "sd.png",
  "Tanzania": "tz.png",
  "Uganda": "ug.png",
  "Ghana": "gh.png",
  "Mozambique": "mz.png",
  "Madagascar": "mg.png",
  "Cameroon": "cm.png",
  "Angola": "ao.png",
  "Ivory Coast": "ci.png",
  "Niger": "ne.png",
  "Burkina Faso": "bf.png",
  "Mali": "ml.png",
  "Malawi": "mw.png",
  "Zambia": "zm.png",
  "Senegal": "sn.png",
  "Chad": "td.png",
  "Somalia": "so.png",
  "Zimbabwe": "zw.png",
  "Guinea": "gn.png",
  "Rwanda": "rw.png",
  "Benin": "bj.png",
  "Burundi": "bi.png",
  "Tunisia": "tn.png",
  "South Sudan": "ss.png",
  "Togo": "tg.png",
  "Sierra Leone": "sl.png",
  "Libya": "ly.png",
  "Congo": "cg.png",
  "Liberia": "lr.png",
  "Central African Republic": "cf.png",
  "Mauritania": "mr.png",
  "Eritrea": "er.png",
  "Namibia": "na.png",
  "Gambia": "gm.png",
  "Botswana": "bw.png",
  "Gabon": "ga.png",
  "Lesotho": "ls.png",
  "Guinea-Bissau": "gw.png",
  "Equatorial Guinea": "gq.png",
  "Mauritius": "mu.png",
  "Eswatini": "sz.png",
  "Djibouti": "dj.png",
  "Comoros": "km.png",
  "Cabo Verde": "cv.png",
  "Sao Tome and Principe": "st.png",
  "Seychelles": "sc.png",

  // Oceania
  "Australia": "au.png",
  "New Zealand": "nz.png",
  "Fiji": "fj.png",
  "Papua New Guinea": "pg.png",
  "Solomon Islands": "sb.png",
  "Vanuatu": "vu.png",
  "Samoa": "ws.png",
  "Kiribati": "ki.png",
  "Tonga": "to.png",
  "Micronesia": "fm.png",
  "Palau": "pw.png",
  "Marshall Islands": "mh.png",
  "Nauru": "nr.png",
  "Tuvalu": "tv.png",

  // Americas
  "Canada": "ca.png",
  "United States": "us.png",
  "Mexico": "mx.png",
  "Guatemala": "gt.png",
  "Honduras": "hn.png",
  "El Salvador": "sv.png",
  "Nicaragua": "ni.png",
  "Costa Rica": "cr.png",
  "Panama": "pa.png",
  "Cuba": "cu.png",
  "Haiti": "ht.png",
  "Dominican Republic": "do.png",
  "Jamaica": "jm.png",
  "Trinidad and Tobago": "tt.png",
  "Bahamas": "bs.png",
  "Brazil": "br.png",
  "Argentina": "ar.png",
  "Colombia": "co.png",
  "Peru": "pe.png",
  "Venezuela": "ve.png",
  "Chile": "cl.png",
  "Ecuador": "ec.png",
  "Bolivia": "bo.png",
  "Paraguay": "py.png",
  "Uruguay": "uy.png",
  "Guyana": "gy.png",
  "Suriname": "sr.png",
  "French Guiana": "gf.png"
};